Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,5 @@
 version: 2.1
+
 orbs:
   node: circleci/node@5.1.0
 
@@ -38,7 +39,15 @@ jobs:
           command: python -m venv venv
       - run:
           name: Activate Virtual Environment
-          command: source venv/bin/activate
+          command: |
+            if [ -f venv/bin/activate ]; then
+              source venv/bin/activate
+            elif [ -f venv/Scripts/activate ]; then
+              source venv/Scripts/activate
+            else
+              echo "Virtual environment activation script not found."
+              exit 1
+            fi
       - run:
           name: Install Python Dependencies
           command: |
